version: "3"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    hostname: localhost
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./nginx-conf/ssl:/etc/nginx/ssl