packages:
  # workers are managed independently; add them here after running pnpm install locally
  - '!**/workers/**'
  - '!**/test/**'
allowBuilds:
  '@parcel/watcher': set this to true or false
  cypress: set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
