name: Lint and Tests
on: workflow_call

jobs:
  lint-and-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.x"

      - name: Run eslint
        run: |
          npm ci
          npm run lint

      - name: Run stylelint
        run: npm run stylelint

      - name: Run jest
        run: npm run test
