name: Lint
on: workflow_call

jobs:
  lint:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.x"

      - name: Run eslint
        run: npm run lint