name: Cypress (preview)
on: workflow_call

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.x"

      - name: Run cypress
        run: npm run cypress:ci -- --record false --key $CYPRESS_KEY
        env:
          CI: true
          BASE_URL: https://${{ github.ref_name }}.reallyluis.pages.dev
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
