name: Cypress (preview)
on:
  workflow_call:
    inputs:
      BASE_URL:
        description: "Base url for cypress tests"
        required: true
        type: string
    secrets:
      CYPRESS_KEY:
        description: "Cypress API key"
        required: true

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.x"

      - name: Cache node_modules
        id: node-modules
        uses: actions/cache@v3
        with:
          path: "./node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('./package-lock.json') }}

      - name: Run install
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run cypress
        run: npm run cypress:ci -- --record false --key $CYPRESS_KEY
        env:
          BASE_URL: ${{ inputs.BASE_URL }}
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
