name: CI/CD
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**/.eslintrc"
      - "**/.gitignore"
      - "**/.npmrc"
      - "**/.stylelintrc.json"
      - ".vscode/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**/.eslintrc"
      - "**/.gitignore"
      - "**/.npmrc"
      - "**/.stylelintrc.json"
      - ".vscode/**"

jobs:
  setup:
    uses: ./.github/workflows/1-setup.yml

  lint:
    needs: setup
    uses: ./.github/workflows/2-lint.yml

  test:
    needs: lint
    uses: ./.github/workflows/3-test.yml

  build:
    needs: test
    uses: ./.github/workflows/4-build.yml
    with:
      COMMIT_SHA: ${{ github.sha }}
    secrets:
      CONTACT_API: ${{ secrets.CONTACT_API }}
      CONTENT_API: ${{ secrets.CONTENT_API }}
      DOMAIN: ${{ secrets.DOMAIN }}
      ENVIRONMENT: production
      FOOTER_MAILTO_EMAIL: ${{ secrets.FOOTER_MAILTO_EMAIL }}

  production:
    if: github.ref_name == 'main'
    needs: build
    uses: ./.github/workflows/5-deploy.yml
    with:
      BASE_URL: https://reallyluis.com
      BRANCH: ${{ github.ref_name }}
      COMMIT_SHA: ${{ github.sha }}
      ENVIRONMENT: production
      RUN_CMD: npm run cypress:ci -- --record --key
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_PAGES_API: ${{ secrets.CLOUDFLARE_PAGES_API }}
      CONTACT_API: ${{ secrets.CONTACT_API }}
      CONTENT_API: ${{ secrets.CONTENT_API }}
      CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
      DOMAIN: ${{ secrets.DOMAIN }}
      FOOTER_MAILTO_EMAIL: ${{ secrets.FOOTER_MAILTO_EMAIL }}

  staging:
    if: github.ref_name != 'main'
    needs: build
    uses: ./.github/workflows/5-deploy.yml
    with:
      BASE_URL: https://staging.reallyluis.pages.dev
      BRANCH: staging
      COMMIT_SHA: ${{ github.sha }}
      ENVIRONMENT: staging
      RUN_CMD: npm run cypress:ci -- --record false --key
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_PAGES_API: ${{ secrets.CLOUDFLARE_PAGES_API }}
      CONTACT_API: ${{ secrets.CONTACT_API }}
      CONTENT_API: ${{ secrets.CONTENT_API }}
      CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
      DOMAIN: ${{ secrets.DOMAIN }}
      FOOTER_MAILTO_EMAIL: ${{ secrets.FOOTER_MAILTO_EMAIL }}
