name: CI
on:
  push:
    branches-ignore:
      - main
      - "feature/**"
      - "release/**"
      - "hotfix/**"
      - "support/**"
    paths-ignore:
      - "**.md"
      - "**/.eslintrc"
      - "**/.gitignore"
      - "**/.npmrc"
      - "**/.stylelintrc.json"
      - ".vscode/**"

jobs:
  setup:
    uses: ./.github/workflows/sub/1-setup.yml

  lint:
    needs: setup
    uses: ./.github/workflows/sub/2-lint.yml

  test:
    needs: lint
    uses: ./.github/workflows/sub/3-test.yml

  build:
    needs: test
    uses: ./.github/workflows/sub/4-build.yml
    with:
      COMMIT_SHA: ${{ github.sha }}
      DOMAIN: reallyluis.com
      ENVIRONMENT: staging
    secrets:
      CONTACT_API: ${{ secrets.CONTACT_API }}
      CONTENT_API: ${{ secrets.CONTENT_API }}
      FOOTER_MAILTO_EMAIL: ${{ secrets.FOOTER_MAILTO_EMAIL }}
