name: CI/CD
on: push

jobs:
  setup:
    uses: ./.github/workflows/1-setup.yml

  lint:
    needs: setup
    uses: ./.github/workflows/2-lint.yml

  test:
    needs: lint
    uses: ./.github/workflows/3-test.yml

  build:
    needs: test
    uses: ./.github/workflows/4-build.yml
    with:
      COMMIT_SHA: ${{ github.sha }}
    secrets:
      CONTACT_API: ${{ secrets.CONTACT_API }}
      CONTENT_API: ${{ secrets.CONTENT_API }}
      DATA: ${{ secrets.DATA }}
      DOMAIN: ${{ secrets.DOMAIN }}
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      FOOTER_MAILTO_EMAIL: ${{ secrets.FOOTER_MAILTO_EMAIL }}

  production:
    if: github.ref_name == 'main'
    needs: build
    uses: ./.github/workflows/5-deploy.yml
    with:
      BASE_URL: https://reallyluis.com
      BRANCH: ${{ github.ref_name }}
      COMMIT_SHA: ${{ github.sha }}
      ENVIRONMENT: production
      RUN_CMD: npm run cypress:ci -- --record --key
      URL: https://reallyluis.com
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_PAGES_API: ${{ secrets.CLOUDFLARE_PAGES_API }}
      CONTACT_API: ${{ secrets.CONTACT_API }}
      CONTENT_API: ${{ secrets.CONTENT_API }}
      CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
      DATA: ${{ secrets.DATA }}
      DOMAIN: ${{ secrets.DOMAIN }}
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      FOOTER_MAILTO_EMAIL: ${{ secrets.FOOTER_MAILTO_EMAIL }}

  staging:
    if: github.ref_name != 'main'
    needs: build
    uses: ./.github/workflows/5-deploy.yml
    with:
      BASE_URL: https://${{ github.ref_name }}.reallyluis.pages.dev
      BRANCH: ${{ github.ref_name }}
      COMMIT_SHA: ${{ github.sha }}
      ENVIRONMENT: staging
      RUN_CMD: npm run cypress:ci -- --record false --key
      URL: https://${{ github.ref_name }}.reallyluis.pages.dev
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_PAGES_API: ${{ secrets.CLOUDFLARE_PAGES_API }}
      CONTACT_API: ${{ secrets.CONTACT_API }}
      CONTENT_API: ${{ secrets.CONTENT_API }}
      CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
      DATA: ${{ secrets.DATA }}
      DOMAIN: ${{ secrets.DOMAIN }}
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      FOOTER_MAILTO_EMAIL: ${{ secrets.FOOTER_MAILTO_EMAIL }}
