name: Cloudflare Pages (branches)
on:
  push:
    branches-ignore:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: "16.17.x"

      - name: Run Install
        run: npm ci
        env:
          CI: true
          CONTACT_API: ${{ secrets.CONTACT_API }}
          CONTENT_API: ${{ secrets.CONTENT_API }}
          DATA: ${{ secrets.DATA }}
          DOMAIN: ${{ secrets.DOMAIN }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          FOOTER_MAILTO_EMAIL: ${{ secrets.FOOTER_MAILTO_EMAIL }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "reallyluis"
          directory: "./dist"
          gitHubToken: ${{ secrets.REPO_TOKEN }}