name: Cypress (branches)
on:
  pull_request:
    branches-ignore:
      - "main"

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.x"

      - name: Run Install
        run: npm ci
        env:
          CI: true
          CONTACT_API: ${{ secrets.CONTACT_API }}
          CONTENT_API: ${{ secrets.CONTENT_API }}
          DATA: ${{ secrets.DATA }}
          DOMAIN: ${{ secrets.DOMAIN }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          FOOTER_MAILTO_EMAIL: ${{ secrets.FOOTER_MAILTO_EMAIL }}

      - name: Run cypress
        run: npm run cypress:ci -- --record false --key $CYPRESS_KEY
        env:
          CI: true
          BASE_URL: https://${{ github.ref_name }}.reallyluis.pages.dev
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
