name: Cypress tests
"on": push
jobs:
  build_cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16.17.x"

      - name: Run Build
        run: |
          npm ci
          npm run build
        env:
          CI: true
          CONTACT_API: ${{ secrets.CONTACT_API }}
          CONTENT_API: ${{ secrets.CONTENT_API }}
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
          DATA: ${{ secrets.DATA }}
          DOMAIN: ${{ secrets.DOMAIN }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          FOOTER_MAILTO_EMAIL: ${{ secrets.FOOTER_MAILTO_EMAIL }}

      - name: Run cypress
        run: npm run cypress:ci