# This workflow will do a clean install, build, and create docker image.

name: Docker CD
'on':
  push:
    branches:
      - main
jobs:
  build-and-push-docker-image:

    runs-on: ubuntu-latest

    name: Docker Build, Tag, Push
    steps:
      - uses: actions/checkout@v2
      - name: Run Build
        run: npm ci && npm run build
        env:
          CI: true
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      - uses: docker/build-push-action@v1
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: docker.pkg.github.com
          repository: reallyluis/reallyluis/reallyluis
          tag_with_sha: true
