name: CI (branches)
on:
  push:
    branches-ignore:
      - "main"

jobs:
  install:
    uses: ./.github/workflows/1-install.yml

  lint-and-tests:
    needs: install
    uses: ./.github/workflows/2-lint-and-tests.yml

  build-and-deploy:
    needs: [install, lint-and-tests]
    uses: ./.github/workflows/3-build-and-deploy.yml
    with:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_PAGES_API: ${{ secrets.CLOUDFLARE_PAGES_API }}
      CONTACT_API: ${{ secrets.CONTACT_API }}
      CONTENT_API: ${{ secrets.CONTENT_API }}
      DATA: ${{ secrets.DATA }}
      DOMAIN: ${{ secrets.DOMAIN }}
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      FOOTER_MAILTO_EMAIL: ${{ secrets.FOOTER_MAILTO_EMAIL }}
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

  e2e:
    needs: [install, lint-and-tests, build-and-deploy]
    uses: ./.github/workflows/4-e2e.yml
    with:
      BASE_URL: https://${{ github.ref_name }}.reallyluis.pages.dev
      CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
