name: CI (branches)
on:
  push:
    branches-ignore:
      - "main"

jobs:
  install:
    uses: ./.github/workflows/1-install.yml

  lint-and-tests:
    needs: install
    uses: ./.github/workflows/2-lint-and-tests.yml

  build-and-deploy:
    needs: [install, lint-and-tests]
    uses: ./.github/workflows/3-build-and-deploy.yml

  e2e:
    needs: [install, lint-and-tests, build-and-deploy]
    uses: ./.github/workflows/4-e2e.yml
