# This workflow will do a clean install, build, lint and testing.

name: Lint and Testing on push
on: [push]
jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run build, lint, and testing.
        run: |
          npm ci
          npm run build
          npm run lint
          npm run test
        env:
          CI: true
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
