# This workflow will tweet about the latest release info on tag.

name: Twitter Post Release
'on':
  push:
    branches:
      - '!*'
    tags:
      - 'v*.*.*'
jobs:
  tweet-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "NEW RELEASE: https://github.com/reallyluis/reallyluis/releases/tag/${{ steps.vars.outputs.tag }}"
          consumer-key: ${{ secrets.TWITTER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
